#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -pe omp 16

source /etc/bashrc

module load subread

GTF=/projectnb/bf528/students/kktu/project_3/rn4_refGene_20180308.gtf

for file in /projectnb/bf528/users/dachsund/project_3/fastq_files/BAM_files/*.bam
    do
        name=$(basename "$file")
        OUT=/projectnb/bf528/students/kktu/project_3/run_actual_samples/$name.txt
        featureCounts -T 16 -a $GTF -o $OUT $file
    done
